name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-eslint:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]    

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: navigate to openapi-forge root directory
        run: echo "$PWD"
        run: cd ./openapi-forge

      - name: test:generators
        run: npm run test:generators