name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-eslint:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]    

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies globally
        run: |
          npm install
          npm install --global

      # - name: test:generators
      #   run: npm run test:generators

      - name: dir
        run: dir


      - name: Upload repo
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: repo-folder
          path: openapi-forge/

      - name: Upload tmp
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tmp-folder
          path: /tmp/

      - name: Upload home
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tmp-folder
          path: /home/